name: Add 10 Numbers

on:
  
  push:
    

jobs:
  add-job:
    runs-on: ubuntu-latest

    steps:
      - name: Add 10 numbers
        run: |
          numbers=(1 2 3 4 5 6 7 8 9 10)
          sum=0
          for n in "${numbers[@]}"; do
            sum=$((sum + n))
          done
          echo "The sum of 10 numbers is: $sum"
