name: Hello World Workflow 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello-vedha:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions! ðŸ‘‹"

      - name: Print date and user
        run: |
          echo "Today is $(date)"
          echo "Triggered by $GITHUB_ACTOR"
